# Generated by Django 2.1 on 2019-05-14 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationsetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='usernotification',
            name='read',
            field=models.BooleanField(default=False),
        ),
    ]
