# Generated by Django 2.1 on 2019-05-08 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_auto_20190508_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='read_time',
            field=models.TextField(default='less than a minute'),
        ),
    ]
