# Generated by Django 2.1 on 2019-05-11 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0006_historicalcomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='first_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='highlighted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='last_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='first_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='highlighted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalcomment',
            name='last_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
